/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HivemindsBackend.EduStructure;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
